name: tic_tac_toe
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
 
  shared_preferences: ^2.3.5
  # audioplayers: ^6.1.0
  flutter_soloud: ^2.1.7 
  cupertino_icons: ^1.0.8
  collection: ^1.19.0
  slide_countdown: ^2.0.2
  # flutter_launcher_icons: ^0.14.3
  url_launcher: ^6.3.1 
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:  
  uses-material-design: false
  
  assets:    
    - assets/images/
    - assets/songs/